CREATE TABLE IF NOT EXISTS pagamentos (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_DEBITO INT NOT NULL,
    CPF_CNPJ VARCHAR(25) NOT NULL,
    METODO_PAGAMENTO VARCHAR(25) NOT NULL,
    NUMERO_CARTAO VARCHAR(25),
    VALOR_PAGAMENTO DECIMAL(10, 2) NOT NULL,
    STATUS_PAGAMENTO VARCHAR(25) NOT NULL
);